

# This file was *autogenerated* from the file haetae-bkz.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_256 = Integer(256); _sage_const_4 = Integer(4); _sage_const_64513 = Integer(64513); _sage_const_1 = Integer(1); _sage_const_1p = RealNumber('1.'); _sage_const_20 = Integer(20)
load("../framework/instance_gen.sage")

verbosity = _sage_const_2 

##(k,\ell-1) is (m,n)/256
#
## HAETAE-120 parameters
#print("============= HAETAE-120")
#n = 3*256
#m = 2*256
#q = 64513
#eta = 1
#D_s = {x : 1./(2*eta+1) for x in range(-eta, eta+1)}
#D_e = D_s
#
#_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
#                                          m, D_e, D_s, verbosity=verbosity)
#
#inst.integrate_q_vectors(q, report_every=20)
#print(" Attack Estimation via GSA + Interesect model ")
#inst.estimate_attack()
#print(" Attack Estimation via simulation + probabilistic model ")
#inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)
#
##HAETAE-180 parameters
#print("============= HAETAE-180")
#
#n = 5*256
#m = 3*256
#q = 64513
#eta = 1
#D_s = {x : 1./(2*eta+1) for x in range(-eta, eta+1)}
#D_e = D_s
#
#_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
#                                          m, D_e, D_s, verbosity=verbosity)
#
#inst.integrate_q_vectors(q, report_every=20)
#print(" Attack Estimation via GSA + Interesect model ")
#inst.estimate_attack()
#print(" Attack Estimation via simulation + probabilistic model ")
#
#inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)

#HAETAE-260 parameters
print("============= HAETAE-260")

n = _sage_const_6 *_sage_const_256 
m = _sage_const_4 *_sage_const_256 
q = _sage_const_64513 
eta = _sage_const_1 
D_s = {x : _sage_const_1p /(_sage_const_2 *eta+_sage_const_1 ) for x in range(-eta, eta+_sage_const_1 )}
D_e = D_s

_, _, inst = initialize_from_LWE_instance(DBDD_predict_diag, n, q,
                                          m, D_e, D_s, verbosity=verbosity)

inst.integrate_q_vectors(q, report_every=_sage_const_20 )
print(" Attack Estimation via GSA + Interesect model ")
inst.estimate_attack()
print(" Attack Estimation via simulation + probabilistic model ")
inst.estimate_attack(probabilistic=True, lift_union_bound=True, silent=False)

